project:
  type: 
  output-dir: docs

website:
  title: "Example_website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: dark
    css: styles.css
    toc: true



